Parameters:
  NameOfService:
    Description: "The name of the service this stack is to be used for."
    Default: "Test Hybris"
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access into the server
    Type: AWS::EC2::KeyPair::KeyName
    Default: "Joseph-ACG-Demo"
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-009d6802948d06e52
    us-west-1:
      AMI: ami-bf5540df
    eu-west-1:
      AMI: ami-3bfab942
    ap-southeast-1:
      AMI: ami-e2adf99e
    ap-southeast-2:
      AMI: ami-43874721    
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Init:
        config: 
          packages: 
            yum:
              httpd: []
              php: []
              java-1.8.0-openjdk-devel: []
          files: 
            /var/www/html/index.php:
              content: !Sub |
                <?php print "Hello world Abs was here!"; ?>
          services: 
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: !Ref ${AWS::StackName}
      KeyName: !Ref KeyName
      UserData:
        'Fn::Base64': 
          !Sub |
            #!/bin/bash -xe            
            # Ensure AWS CFN Bootstrap is the latest
            yum install -y aws-cfn-bootstrap wget
            # Install the files and packages from the metadata
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance  --region ${AWS::Region}
            
            # Custom Code
            rpm --import 'http://nginx.org/keys/nginx_signing.key'
            echo '[nginx]
            name=nginx repo
            baseurl=http://nginx.org/packages/centos/7/x86_64
            gpgcheck=1
            enabled=1' | sudo bash -c 'cat > /etc/yum.repos.d/nginx.repo'
            
            # install nginx
            yum install -y nginx
            # add log folder for nginx
            mkdir -p /var/log/nginx
            # config nginx
            wget https://raw.githubusercontent.com/chenjianAgain/intro-to-CloudFormation_AC/master/03%20Setting%20up%20an%20EC2%20Instance/nginx.conf && sudo cp nginx.conf /etc/nginx/nginx.conf
            # start nginx
            systemctl enable nginx
            systemctl start nginx

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open Ports 22 and 80
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
Outputs:
  Website:
    Description: The Public DNS for the EC2 Instance
    Value: !Sub 'http://${EC2Instance.PublicDnsName}'
